import Image from "next/image";

const phone = "+79999774908";
const categories = [
  { title: "Освещение", text: "Светильники, лампы, уличный свет и комплектующие.", image: "/images/photo-15.jpg" },
  { title: "Розетки и выключатели", text: "Классические и современные серии для любого интерьера.", image: "/images/photo-10.jpg" },
  { title: "Автоматика и щиты", text: "Автоматы, УЗО, реле, клеммы и оборудование для сборки.", image: "/images/photo-11.jpg" },
  { title: "Свет для дома", text: "Точечные, накладные и трековые светильники.", image: "/images/photo-7.jpg" },
];
const gallery = [[14,"Магазин «Электрика»"],[13,"Светодиодное оборудование"],[9,"Электрощиты и комплектующие"],[10,"Выключатели и розетки"],[11,"Автоматика"],[6,"Монтажные аксессуары"],[7,"Встраиваемые светильники"],[8,"Светильники"],[2,"Ретро-розетки"],[1,"Автоматические выключатели"],[23,"Лампы и источники света"],[24,"Декоративные светильники"],[25,"Электротехническое оборудование"],[26,"Автоматика и учёт"],[19,"Крепёж и расходные материалы"],[21,"Точечные светильники"],[20,"LED-оборудование"],[22,"Светильники и розетки"],[16,"Ретро-электрика"],[17,"Прожекторы"],[18,"Удлинители и аксессуары"],[12,"Электрооборудование"]] as const;
const certificates = [[3,"ДКС","Официальный партнёр"],[4,"Systeme Electric","Официальный партнёр"],[5,"Dekraft","Официальный розничный партнёр"]] as const;

export default function Home() {
  return <main>
    <header className="site-header" id="top"><div className="container header-inner"><a className="brand" href="#top" aria-label="Торговый дом Электрика"><Image src="/images/logo.jpg" alt="Логотип Торговый дом Электрика" width={48} height={48} priority /><span>Торговый дом <strong>Электрика</strong></span></a><nav aria-label="Основная навигация"><a href="#catalog">Товары</a><a href="#gallery">Фотографии</a><a href="#certificates">Сертификаты</a><a href="#contacts">Контакты</a></nav><a className="header-phone" href={`tel:${phone}`}>{phone}</a></div></header>
    <section className="hero" aria-labelledby="hero-title"><Image className="hero-image" src="/images/photo-14.jpg" alt="Фасад магазина Электрика" fill priority sizes="100vw" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow">Торговый дом «Электрика»</p><h1 id="hero-title">Всё для света,<br />дома и ремонта</h1><p className="hero-text">Электротовары для дома, дачи и профессионального монтажа. Поможем подобрать нужное — быстро и по делу.</p><a className="button" href={`tel:${phone}`}>Позвонить: {phone}</a></div></section>
    <section className="section" id="catalog"><div className="container"><div className="section-heading"><p className="eyebrow">Ассортимент</p><h2>Подберём всё необходимое</h2></div><div className="category-grid">{categories.map((item) => <article className="category-card" key={item.title}><div className="category-photo"><Image src={item.image} alt={item.title} fill sizes="(max-width: 720px) 100vw, 25vw" /></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="info-band" id="contacts"><div className="container info-grid"><div><span>Адрес</span><strong>ул. Ленина, 83<br />село Павловская Слобода</strong></div><div><span>Режим работы</span><strong>Без выходных<br />09:00–18:00</strong></div><div><span>Телефон</span><a href={`tel:${phone}`}>{phone}</a></div><div><span>Консультация</span><strong>Поможем с выбором<br />и комплектацией</strong></div></div></section>
    <section className="section gallery-section" id="gallery"><div className="container"><div className="section-heading"><p className="eyebrow">В магазине</p><h2>Фотографии ассортимента</h2><p>Большой выбор оборудования, освещения и аксессуаров в наличии.</p></div><div className="gallery-grid">{gallery.map(([number, caption]) => <figure className="gallery-card" key={number}><Image src={`/images/photo-${number}.jpg`} alt={caption} fill sizes="(max-width: 650px) 50vw, (max-width: 1000px) 33vw, 25vw" /><figcaption>{caption}</figcaption></figure>)}</div></div></section>
    <section className="section certificates" id="certificates"><div className="container"><div className="section-heading"><p className="eyebrow">Официальные партнёры</p><h2>Сертификаты</h2><p>Работаем с проверенными производителями и предлагаем сертифицированную продукцию.</p></div><div className="certificates-grid">{certificates.map(([number, name, description]) => <article className="certificate" key={number}><Image src={`/images/photo-${number}.jpg`} alt={`Сертификат ${name}`} width={580} height={820} /><div><h3>{name}</h3><p>{description}</p></div></article>)}</div></div></section>
    <footer><div className="container footer-inner"><span>Торговый дом «Электрика»</span><a href={`tel:${phone}`}>{phone}</a><small>webdizayntut@mail.ru</small></div></footer>
  </main>;
}
